source("Map.R")



#generates customers
generateCustomers=function(){
  # customers generated by normal distribution
  customerAmount= rnorm(1,100,10)

  #adds all customers to a list with random information for their location
  customerList = c()
  for(i in 1:customerAmount){ # generates customers and adds it to a vector of customer objects
    orderAmount=rpois(1,1)
    while(orderAmount==0){
      orderAmount=rpois(1,1)
    }
    
    denistyProb=runif(1,1,9343)

    if(denistyProb<137){
      #Berkshire
      xValue=runif(1,10,30)
      yValue=runif(1,60,150)



    }else if(denistyProb<238){
      #Franklin
      xValue=runif(1,30,60)
      yValue=runif(1,120,150)
    }else if(denistyProb<544){
      #Hampshire
      xValue=runif(1,30,60)
      yValue=runif(1,90,120)
    }else if(denistyProb<1304){
      #Hampden
      xValue=runif(1,30,60)
      yValue=runif(1,60,90)


    }else if(denistyProb<1848){
      #Worcester
      xValue=runif(1,60,90)
      yValue=runif(1,60,150)


    }else if(denistyProb<7148){
      #Essex +Middlesex + Norfolk
      xValue=runif(1,90,120)
      yValue=runif(1,60,150)
    }else if(denistyProb<9343){
      #Bristol + Plymoth + Barnstable + Dukes + Nantucket
      xValue=runif(1,120,150)
      yValue=runif(1,10,90)
    }
    newCust = new("customer", xcoord=xValue, ycoord=yValue, demand=orderAmount)
    customerList = c(customerList, newCust)
  }
  return (customerList)
}

#plots the customers 
plotCustomers=function(customerList,newCheckpoint){
  day=newCheckpoint@day
  checkpoint=newCheckpoint@checkpoint
  makeMap(day,checkpoint)
  for (i in 1:length(customerList)){  # iterates over the customer vector and plots their locations
    points(customerList[[i]]@xcoord,customerList[[i]]@ycoord)
  }
}

#main function to generate and plot customers and warehouse returning the list of all customers
getCustomers=function(newCheckpoint){ # returns list of customers and plots them on the map
  customerList=generateCustomers()
  plotCustomers(customerList,newCheckpoint)
  for(i in 1:length(newCheckpoint@warehouses)){
    points(newCheckpoint@warehouses[[i]]@xcoord,newCheckpoint@warehouses[[i]]@ycoord, pch=24, col="red", bg="blue")
  }
  return(customerList)
}